# 13C — Event chronology across 2022, 2023, 2024 and 2025

**Priority 3.** Revisit first **observed** high-low-VV dates, within-orbit transition intervals and threshold dependence. The available scene dates cannot identify an exact water-onset date.

**Execution:** This is a source workflow, NOT results. A successful extract needs your own data / Earth Engine session. Do not treat low-VV detections as validated water, flood depth or methane flux.

In [1]:
# Every notebook uses the same ROOT; no hard-coded drive or EE project ID.
from pathlib import Path
import os, sys
starting = Path(os.environ.get("HAKALUKI_ROOT", Path.cwd())).expanduser().resolve()
for candidate in [starting, *starting.parents]:
    if (candidate/"src/analysis13/core.py").is_file():
        ROOT = candidate
        break
else:
    raise FileNotFoundError("Extract the ZIP into the project root and open Jupyter there, or set HAKALUKI_ROOT")
sys.path.insert(0, str(ROOT))
print("Research root:", ROOT)

Research root: F:\Wetland Test\Hakaluki_Haor_Wetland_Test_Jupyter_GEE_Project

## Compute offline transition chronology

Uses your executed Notebook 12 CSV; no new remote data or models required.

In [2]:
from src.analysis13.offline import run_offline, consecutive_transitions
from src.analysis13.core import load_scenes
import pandas as pd
scenes=load_scenes(ROOT)
print(run_offline(ROOT))
transition=consecutive_transitions(scenes)
display(transition.sort_values('delta_m17_km2',ascending=False).head(15))

{'created_utc': '2026-10-14T17:09:17.310664+00:00', 'status': 'exploratory_reanalysis_of_uploaded_scene12_outputs_not_earth_engine_rerun', 'n_scenes': 94, 'n_transitions': 86, 'n_same_sign': 66, 'n_strong_same_sign_20km2': 12, 'years': [2022, 2023, 2024, 2025], 'max_threshold_span_km2': 133.19901915697625, 'all_numerics_from': 'scene12_S1_per_acquisition_2022_2025.csv', 'limitations': 'Area screening is unvalidated; acquisition differences are not directly water change; fixed VV thresholds and orbit effects remain.'}

,year,pass,relative_orbit,before_id,after_id,before_utc,after_utc,before_local,after_local,days_between,delta_m19_km2,delta_m17_km2,delta_m15_km2,same_sign_all_thresholds,strong_change_all_thresholds_20km2,n_scenes_between
1,2022,ASCENDING,41,S1A_IW_GRDH_1SDV_20220511T115642_20220511T1157...,S1A_IW_GRDH_1SDV_20220523T115643_20220523T1157...,2022-05-11 11:56:42+00:00,2022-05-23 11:56:43+00:00,2022-05-11 17:56:42+06:00,2022-05-23 17:56:43+06:00,12.000012,119.468040,121.290465,116.880707,True,True,0
27,2023,ASCENDING,41,S1A_IW_GRDH_1SDV_20230611T115649_20230611T1157...,S1A_IW_GRDH_1SDV_20230623T115650_20230623T1157...,2023-06-11 11:56:49+00:00,2023-06-23 11:56:50+00:00,2023-06-11 17:56:49+06:00,2023-06-23 17:56:50+06:00,12.000012,121.967617,121.111647,118.364733,True,True,0
26,2023,DESCENDING,77,S1A_IW_GRDH_1SDV_20230601T234747_20230601T2348...,S1A_IW_GRDH_1SDV_20230625T234748_20230625T2348...,2023-06-01 23:47:47+00:00,2023-06-25 23:47:48+00:00,2023-06-02 05:47:47+06:00,2023-06-26 05:47:48+06:00,24.000012,113.524305,116.114546,112.356956,True,True,0
48,2024,DESCENDING,77,S1A_IW_GRDH_1SDV_20240526T234750_20240526T2348...,S1A_IW_GRDH_1SDV_20240607T234750_20240607T2348...,2024-05-26 23:47:50+00:00,2024-06-07 23:47:50+00:00,2024-05-27 05:47:50+06:00,2024-06-08 05:47:50+06:00,12.000000,128.497319,111.100060,105.892782,True,True,0
47,2024,ASCENDING,41,S1A_IW_GRDH_1SDV_20240524T115652_20240524T1157...,S1A_IW_GRDH_1SDV_20240605T115652_20240605T1157...,2024-05-24 11:56:52+00:00,2024-06-05 11:56:52+00:00,2024-05-24 17:56:52+06:00,2024-06-05 17:56:52+06:00,12.000000,122.070107,105.147028,99.800257,True,True,0
0,2022,DESCENDING,77,S1A_IW_GRDH_1SDV_20220501T234740_20220501T2348...,S1A_IW_GRDH_1SDV_20220513T234740_20220513T2348...,2022-05-01 23:47:40+00:00,2022-05-13 23:47:40+00:00,2022-05-02 05:47:40+06:00,2022-05-14 05:47:40+06:00,12.000000,62.626909,71.236079,73.835320,True,True,0
64,2025,ASCENDING,41,S1A_IW_GRDH_1SDV_20250507T115645_20250507T1157...,S1A_IW_GRDH_1SDV_20250519T115644_20250519T1157...,2025-05-07 11:56:45+00:00,2025-05-19 11:56:44+00:00,2025-05-07 17:56:45+06:00,2025-05-19 17:56:44+06:00,11.999988,53.875768,56.847190,57.770800,True,True,0
2,2022,DESCENDING,77,S1A_IW_GRDH_1SDV_20220513T234740_20220513T2348...,S1A_IW_GRDH_1SDV_20220525T234741_20220525T2348...,2022-05-13 23:47:40+00:00,2022-05-25 23:47:41+00:00,2022-05-14 05:47:40+06:00,2022-05-26 05:47:41+06:00,12.000012,63.720174,56.251241,52.719625,True,True,0
65,2025,DESCENDING,77,S1A_IW_GRDH_1SDV_20250509T234743_20250509T2348...,S1A_IW_GRDH_1SDV_20250521T234742_20250521T2348...,2025-05-09 23:47:43+00:00,2025-05-21 23:47:42+00:00,2025-05-10 05:47:43+06:00,2025-05-22 05:47:42+06:00,11.999988,10.520288,51.156536,67.349069,True,False,0
66,2025,ASCENDING,41,S1A_IW_GRDH_1SDV_20250519T115644_20250519T1157...,S1A_IW_GRDH_1SDV_20250531T115644_20250531T1157...,2025-05-19 11:56:44+00:00,2025-05-31 11:56:44+00:00,2025-05-19 17:56:44+06:00,2025-05-31 17:56:44+06:00,12.000000,38.042484,47.901719,55.824491,True,True,0
67,2025,DESCENDING,77,S1A_IW_GRDH_1SDV_20250521T234742_20250521T2348...,S1A_IW_GRDH_1SDV_20250602T234742_20250602T2348...,2025-05-21 23:47:42+00:00,2025-06-02 23:47:42+00:00,2025-05-22 05:47:42+06:00,2025-06-03 05:47:42+06:00,12.000000,4.651309,42.091963,66.479747,True,False,0
68,2025,ASCENDING,41,S1A_IW_GRDH_1SDV_20250531T115644_20250531T1157...,S1A_IW_GRDH_1SDV_20250612T115643_20250612T1157...,2025-05-31 11:56:44+00:00,2025-06-12 11:56:43+00:00,2025-05-31 17:56:44+06:00,2025-06-12 17:56:43+06:00,11.999988,-0.555807,34.287890,25.578460,False,False,0
73,2025,DESCENDING,77,S1A_IW_GRDH_1SDV_20250708T234740_20250708T2348...,S1A_IW_GRDH_1SDV_20250720T234739_20250720T2348...,2025-07-08 23:47:40+00:00,2025-07-20 23:47:39+00:00,2025-07-09 05:47:40+06:00,2025-07-21 05:47:39+06:00,11.999988,100.106962,32.165155,-0.324218,False,False,0
51,2024,ASCENDING,41,S1A_IW_GRDH_1SDV_20240617T115651_20240617T1157...,S1A_IW_GRDH_1SDV_20240629T115651_20240629T1157...,2024-06-17 11:56:51+00:00,2024-06-29 11:56:51+00:00,2024-06-17 17:56:51+06:00,2024-06-29 17:56:51+06:00,12.000000,90.955042,20.558489,1.442414,True,False,0
23,2023,ASCENDING,41,S1A_IW_GRDH_1SDV_20230518T115648_20230518T1157...,S1A_IW_GRDH_1SDV_20230530T115649_20230530T1157...,2023-05-18 11:56:48+00:00,2023-05-30 11:56:49+00:00,2023-05-18 17:56:48+06:00,2023-05-30 17:56:49+06:00,12.000012,14.941178,17.659098,19.953985,True,False,0

## First observed high-screening brackets

The user-defined 85% fraction is a screening diagnostic, **not an inundation onset threshold**. Compare at least 75%, 85% and 90% to quantify arbitrariness.

In [3]:
from src.analysis13.hydrology import first_observed_threshold_crossings
for frac in (0.75,0.85,0.90):
    print('\nILLUSTRATIVE nominal low-VV fraction:',frac)
    display(first_observed_threshold_crossings(scenes,frac))

ILLUSTRATIVE nominal low-VV fraction: 0.75

,year,pass,relative_orbit,before_local,first_above_local,interval_days,status
0,2022,ASCENDING,41,2022-05-11 17:56:42+06:00,2022-05-23 17:56:43+06:00,12.000012,first_observed_crossing_bracket
1,2022,DESCENDING,77,2022-05-14 05:47:40+06:00,2022-05-26 05:47:41+06:00,12.000012,first_observed_crossing_bracket
2,2023,ASCENDING,41,2023-06-11 17:56:49+06:00,2023-06-23 17:56:50+06:00,12.000012,first_observed_crossing_bracket
3,2023,DESCENDING,77,2023-06-02 05:47:47+06:00,2023-06-26 05:47:48+06:00,24.000012,first_observed_crossing_bracket
4,2024,ASCENDING,41,2024-05-24 17:56:52+06:00,2024-06-05 17:56:52+06:00,12.000000,first_observed_crossing_bracket
5,2024,DESCENDING,77,2024-05-27 05:47:50+06:00,2024-06-08 05:47:50+06:00,12.000000,first_observed_crossing_bracket
6,2025,ASCENDING,41,2025-05-31 17:56:44+06:00,2025-06-12 17:56:43+06:00,11.999988,first_observed_crossing_bracket
7,2025,DESCENDING,77,2025-07-09 05:47:40+06:00,2025-07-21 05:47:39+06:00,11.999988,first_observed_crossing_bracket

ILLUSTRATIVE nominal low-VV fraction: 0.85

,year,pass,relative_orbit,before_local,first_above_local,interval_days,status
0,2022,ASCENDING,41,2022-05-11 17:56:42+06:00,2022-05-23 17:56:43+06:00,12.000012,first_observed_crossing_bracket
1,2022,DESCENDING,77,2022-05-14 05:47:40+06:00,2022-05-26 05:47:41+06:00,12.000012,first_observed_crossing_bracket
2,2023,ASCENDING,41,2023-06-11 17:56:49+06:00,2023-06-23 17:56:50+06:00,12.000012,first_observed_crossing_bracket
3,2023,DESCENDING,77,2023-06-02 05:47:47+06:00,2023-06-26 05:47:48+06:00,24.000012,first_observed_crossing_bracket
4,2024,ASCENDING,41,2024-05-24 17:56:52+06:00,2024-06-05 17:56:52+06:00,12.000000,first_observed_crossing_bracket
5,2024,DESCENDING,77,2024-05-27 05:47:50+06:00,2024-06-08 05:47:50+06:00,12.000000,first_observed_crossing_bracket
6,2025,ASCENDING,41,2025-05-31 17:56:44+06:00,2025-06-12 17:56:43+06:00,11.999988,first_observed_crossing_bracket
7,2025,DESCENDING,77,2025-07-09 05:47:40+06:00,2025-07-21 05:47:39+06:00,11.999988,first_observed_crossing_bracket

ILLUSTRATIVE nominal low-VV fraction: 0.9

,year,pass,relative_orbit,before_local,first_above_local,interval_days,status
0,2022,ASCENDING,41,2022-05-11 17:56:42+06:00,2022-05-23 17:56:43+06:00,12.000012,first_observed_crossing_bracket
1,2022,DESCENDING,77,2022-05-14 05:47:40+06:00,2022-05-26 05:47:41+06:00,12.000012,first_observed_crossing_bracket
2,2023,ASCENDING,41,2023-06-11 17:56:49+06:00,2023-06-23 17:56:50+06:00,12.000012,first_observed_crossing_bracket
3,2023,DESCENDING,77,2023-06-02 05:47:47+06:00,2023-06-26 05:47:48+06:00,24.000012,first_observed_crossing_bracket
4,2024,ASCENDING,41,2024-05-24 17:56:52+06:00,2024-06-05 17:56:52+06:00,12.000000,first_observed_crossing_bracket
5,2024,DESCENDING,77,2024-05-27 05:47:50+06:00,2024-06-08 05:47:50+06:00,12.000000,first_observed_crossing_bracket
6,2025,ASCENDING,41,2025-05-31 17:56:44+06:00,2025-06-12 17:56:43+06:00,11.999988,first_observed_crossing_bracket
7,2025,DESCENDING,77,2025-07-09 05:47:40+06:00,2025-07-21 05:47:39+06:00,11.999988,first_observed_crossing_bracket

## Interpretation checks

Inspect May 11→23 2022, June 11→23 2023, June 2024 radiometric outlier, June 2025 descending and compare with the paired change maps from 13B.

In [4]:
print('Reminder: temporal bracketing is observational; no linearly interpolated extent or water-depth conclusion.')
print('Next: use 13B to test which within-orbit changes occur at the same pixels.')

Reminder: temporal bracketing is observational; no linearly interpolated extent or water-depth conclusion.
Next: use 13B to test which within-orbit changes occur at the same pixels.